before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - binary: gcopy
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
universal_binaries:
  - replace: true
brews:
  -
    name: gcopy
    homepage: "https://github.com/TheDen/gcopy"
    tap:
      owner: TheDen
      name: homebrew-gcopy
    commit_author:
      name: TheDen
      email: gcopy@theden.sh
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
checksum:
  name_template: 'checksums.txt'
