[default]
locale = "en-au"
extend-ignore-words-re = ["PN", "LICENSE", "LICENCE"]

[default.extend-identifiers]
center = "center"

[files]
ignore-vcs = true
extend-exclude = [
  "vendor",
  ".git",
  "*.drawio",
  "go.mod",
  "go.sum",
  "cluster-embedded"
]


